export const AUTH_ERROR_CODES = {
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  ACCESS_TOKEN_MISSING: "ACCESS_TOKEN_MISSING",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  FORBIDDEN: "FORBIDDEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  SESSION_REVOKED: "SESSION_REVOKED",
} as const;

export type AuthErrorCode = keyof typeof AUTH_ERROR_CODES;
